classroom/urls.py
from django.urls import path
from .views import TeacherTemplateView, ContactFormView, TeacherCreateView, TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView
from .models import Teacher
from . import views



app_name = 'classroom'


urlpatterns = [
    path('', TeacherTemplateView.as_view(), name = 'home'),
    path('contact_form/',ContactFormView.as_view(), name =  'contact_form'),
    path('create/', TeacherCreateView.as_view(), name= 'create'),
    path('teacher_list', TeacherListView.as_view(), name = 'teacher_list'),
    path('detail_view/<int:pk>', TeacherDetailView.as_view(), name= 'detail_view'),
    path('teacher_update/<int:pk>', TeacherUpdateView.as_view(), name = 'teacher_update'),
    path('teacher_delete/<int:pk>', TeacherDeleteView.as_view(), name = 'teacher_delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('classroom/', include('classroom.urls')),
    path('admin/', admin.site.urls),
]

classroom/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length = 30)

    def __str__(self):
        return f'{self.first_name} {self.last_name} teaches {self.subject}'

classroom/forms.py
from tkinter import Widget
from django import forms
from django.forms import Textarea



class ContactFrom(forms.Form):
    name = forms.CharField()
    Message = forms.CharField(widget=forms.Textarea)

    

classroom/views.py
from msilib.schema import ListView
from typing import List
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView

from .forms import ContactFrom
from .models import Teacher

# Create your views here.


class TeacherTemplateView(TemplateView):
    template_name = 'classroom/home.html'


class ContactFormView(FormView):
    form_class = ContactFrom
    template_name = 'classroom/contact.html'

    success_url = reverse_lazy('classroom:home')

    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)


class TeacherCreateView(CreateView):
    model = Teacher 
    fields = '__all__'

    success_url = reverse_lazy('classroom:home')

class TeacherListView(ListView):
    model = Teacher

class TeacherDetailView(DetailView):
    model = Teacher 


class TeacherUpdateView(UpdateView):
    model = Teacher 
    fields = '__all__'
    success_url = reverse_lazy('classroom:teacher_list')


class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')

classroom/templates/classroom/contact.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classroom</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Contact Form</a>
          </li>
        </ul>
      </div>
    </div>
</nav>
<br>
<br>
<br>


<h3>Write Your Message </h3>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

<a href="{% url 'classroom:home' %}">Click here to return to Homepage </a>

<script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>

classroom/templates/classroom/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classroom</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>

    
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'classroom:home' %}">Student Portal</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'classroom:contact_form' %}">Contact</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'classroom:teacher_list' %}">List</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>



  <br>
  <br>
  <br>
  

<ul>
  <li>
    <a href="{% url 'classroom:teacher_list' %}">Click here to view Student List </a>
  </li>
  <li>
    <a href="{% url 'classroom:create' %}">Click here to Add Student List</a>
  </li>
</ul>

  
  
  
  
      <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>

classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this Teacher </h1>
<h2>{{teacher}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="submit">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>Detail View </h1>
{{teacher}}

classroom/templates/classroom/teacher_form.html
<H2> Teacher Form</H2>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<a href="{% url 'classroom:home' %}">Click here to return to Homepage </a>

classroom/templates/classroom/teacher_list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classroom</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Student</a>
          </li>
        </ul>
      </div>
    </div>
</nav>
<br>
<br>
<br>


<div class="container">
    <h3> Student List </h3>
<ul>
    {% for teacher in object_list %}
        <li>
            <a href="/classroom/detail_view/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name }}</a>
        </li>
        <ul>
            <li>
                <a href="/classroom/teacher_update/{{teacher.id}}"> Update {{teacher.first_name}} {{teacher.last_name }} Information</a>
            </li>
            <li>
                <a href="/classroom/teacher_delete/{{teacher.id}}"> Delete {{teacher.first_name}} {{teacher.last_name }} Information</a>
            </li>
            
        </ul>
    {% endfor %}
</ul>
<a href="{% url 'classroom:home' %}">Click here to view Teacher List </a>
</div>



<script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>